export enum Color {
    Blue = 'blue',
    Orange = 'orange',
    Yellow = 'yellow',
    Amber = 'amber',
    Green = 'green',
    Emerald = 'emerald',
    Violet = 'violet',
    Cyan = 'cyan',
    Rose = 'rose',
    Purple = 'purple',
    Red = 'red',
    Pink = 'pink',
}

export const availableTags: { name: string; color: Color }[] = [
    { name: "Mixed Reality", color: Color.Emerald },
    { name: "Web Development", color: Color.Blue },
    { name: "Interaktionsdesign", color: Color.Violet },
    { name: "WebSockets", color: Color.Green },
    { name: "Docker", color: Color.Cyan },
    { name: "User Experience", color: Color.Orange },
    { name: "Frontend Development", color: Color.Amber },
    { name: "Swift", color: Color.Yellow },
    { name: "SwiftUI", color: Color.Green },
    { name: "Augmented Reality", color: Color.Cyan },
    { name: "Flutter", color: Color.Rose },
    { name: "Augmented Reality", color: Color.Purple },
    { name: "Real Time Database", color: Color.Red },
    { name: "Unity", color: Color.Pink },
    { name: "C#", color: Color.Blue },
    { name: "Elektrotechnik", color: Color.Orange },
    { name: "Game Design", color: Color.Yellow },
  ];